#!/bin/bash

if [ $# -ne 1 ]
    then
        echo "Run with 'activate' argument!"
        exit
    fi

GITREVS=`git rev-list --count HEAD`
GITHASH=`git rev-parse --short HEAD`
DATE=`date +"%Y-%m-%d %H:%M"`

cat > src/lib/abs/ABSMainHeaderConfig.hpp << EOF
#define ABS_CONFIG_VERSION  "3.x"
#define ABS_VERSION         "3.${GITREVS}.${GITHASH}"
#define ABS_BUILDTIME       "${DATE}"
EOF

echo ""
echo "ABS Revision: 3.$GITREVS.$GITHASH ($DATE)"

