#!/bin/bash

if [ $# -ne 1 ]
    then
        echo "Run with 'activate' argument!"
        exit
    fi

GITREVS=`git rev-list --count HEAD`
GITHASH=`git rev-parse --short HEAD`
DATE=`date +"%Y-%m-%d %H:%M"`

sed -e "s/GITREVS/$GITREVS/g" -e "s/GITHASH/$GITHASH/g" -e "s/DATE/$DATE/g" \
    src/lib/abs/ABSMainHeader.cpp > src/lib/abs/_ABSMainHeader.cpp

mv -f src/lib/abs/_ABSMainHeader.cpp src/lib/abs/ABSMainHeader.cpp

echo ""
echo "ABS Revision: 3.$GITREVS.$GITHASH ($DATE)"

