#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Run with 'activate' argument!"
    exit
fi

GITREVS=`git rev-list --count HEAD`
if [ $? -ne 0 ]; then exit 1; fi

GITHASH=`git rev-parse --short HEAD`
if [ $? -ne 0 ]; then exit 1; fi

DATE=`date +"%Y-%m-%d %H:%M"`

cat > src/lib/abs/ABSMainHeaderConfig.hpp << EOF
#define ABS_CONFIG_VERSION  "4.x"
#define ABS_VERSION         "4.${GITREVS}.${GITHASH}"
#define ABS_BUILDTIME       "${DATE}"
EOF
if [ $? -ne 0 ]; then exit 1; fi

echo ""
echo "ABS Revision: 4.$GITREVS.$GITHASH ($DATE)"

