#!/bin/bash
# ==============================================================================
# ABS
# (c) 2012, Petr Kulhanek, kulhanek@chemi.muni.cz
# (c) 2008-2009, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.9
# (c) 2006, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.8
# (c) 2005, Petr Kulhanek, kulhanek@chemi.muni.cz
# based on LCC module v1 - v5
# (c) 2001-2004, Petr Kulhanek, kulhanek@chemi.muni.cz
# ==============================================================================
#
# required input
# INF_KILL_MAIN_NODE
# INF_KILL_WORK_DIR
# INF_KILL_WHOLE_NAME
# INF_KILL_JOB_KEY

# global setup
INF_SSH_OPTIONS=`$ABS_ROOT/sbin/abs-get-setup-item INF_SSH_OPTIONS`
if [ $? -ne 0 ]; then INF_SSH_OPTIONS="-o StrictHostKeyChecking=no"; fi
export INF_SSH_OPTIONS

# soft kill mode - call kill script in the working directory ...

if [ -n "$INF_KILL_MAIN_NODE" ] && [ -n "$INF_KILL_JOB_KEY" ] && \
   [ -n "$INF_KILL_WORK_DIR" ] && [ -n "$INF_KILL_WHOLE_NAME" ]; then
   echo ""
   echo "Calling the kill script $INF_KILL_MAIN_NODE:$INF_KILL_WORK_DIR/$INF_KILL_WHOLE_NAME.kill $INF_KILL_JOB_KEY ..."
   ssh -x $INF_SSH_OPTIONS $INF_KILL_MAIN_NODE " \
        cd \"$INF_KILL_WORK_DIR\"; \
        if [ \$? -ne 0 ]; then \
            echo \"\" >&2; \
            echo \" >>> ERROR: Unable to set the working directory '$INF_KILL_WORK_DIR'!\" >&2; \
            echo \"\" >&2; \
            exit 1; \
        fi; \
        if ! [ -f \"${INF_KILL_WHOLE_NAME}.kill\" ]; then \
            echo \"\" >&2; \
            echo \" >>> ERROR: Unable to find the kill script '${INF_KILL_WHOLE_NAME}.kill'!\" >&2; \
            echo \"\" >&2; \
            exit 1; \
        fi
        bash \"${INF_KILL_WHOLE_NAME}.kill\" \"$INF_KILL_JOB_KEY\"; \
        "
    exit $?
fi

# not supported
exit 1
