#!/bin/bash
# =============================================================================
# ABS
# (c) 2008-2009, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.9
# (c) 2006, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.8
# (c) 2005, Petr Kulhanek, kulhanek@chemi.muni.cz
# based on LCC module v1 - v5
# (c) 2001-2004, Petr Kulhanek, kulhanek@chemi.muni.cz
# =============================================================================

echo ""
echo "# ------------------------------------------------------------------------------"
echo "# L3: Copy input job data ..."
echo "# ------------------------------------------------------------------------------"
echo "User identity ..."
echo "UID   : `id`"
echo "Umask : `umask`"
echo

if [ -n "$INF_EXCLUDED_FILES" ]; then
echo " Excluded files: $INF_EXCLUDED_FILES"
else
echo " Excluded files: -none-"
fi

# create file with excluded files
# ${INF_WHOLE_NAME}.infout has to be excluded because of pstart
echo "${INF_WHOLE_NAME}.infout" > $TMPDIR/${_TNAME_}.excluded
echo "*#???.*"  >> $TMPDIR/${_TNAME_}.excluded
echo "pjob???" >> $TMPDIR/${_TNAME_}.excluded
echo "$INF_EXCLUDED_FILES" | tr ";" "\n" >> $TMPDIR/${_TNAME_}.excluded
echo " Final exclusion list:"
cat $TMPDIR/${_TNAME_}.excluded | awk '{ printf("   %s\n",$0); }'
echo ""

case $INF_SYNC_MODE in
    sync | nosync )
        if [ "$INF_REMOTE_JOBDIR" == "YES" ]; then
            echo " Copy mode     : remote rsync"
            echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
            rsync -av --no-g --exclude-from="$TMPDIR/${_TNAME_}.excluded" -e "ssh -o \"StrictHostKeyChecking=no\"" "$INF_JOB_MACHINE:$INF_JOB_PATH/" "$INF_WORK_DIR/"

            if [ $? -ne 0 ]; then
                echo "" >&2
                echo " ERROR: Unable to copy the input job data to the main computational node!" >&2
                echo "" >&2
                exit 1
            fi
            echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
        else
            echo " Copy mode     : local rsync"
            echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
            rsync -av --no-g --exclude-from="$TMPDIR/${_TNAME_}.excluded" "$INF_JOB_PATH/" "$INF_WORK_DIR/"

            if [ $? -ne 0 ]; then
                echo "" >&2
                echo " ERROR: Unable to copy the input job data to the main computational node!" >&2
                echo "" >&2
                exit 1
            fi
            echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
        fi
    ;;
    jobdir )
        echo " The job will be executed in the input job directory, no data are copied ..."
    ;;
esac

rm -f $TMPDIR/${_TNAME_}.excluded

echo " Success."

# ------------------------------------------------------------------------------

exit 0





