#!/bin/bash
# ==============================================================================
# ABS
# (c) 2012, Petr Kulhanek, kulhanek@chemi.muni.cz
# (c) 2008-2009, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.9
# (c) 2006, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.8
# (c) 2005, Petr Kulhanek, kulhanek@chemi.muni.cz
# based on LCC module v1 - v5
# (c) 2001-2004, Petr Kulhanek, kulhanek@chemi.muni.cz
# ==============================================================================

# ------------------------------------------------------------------------------
# mark this job as INFINITY job, this is used by module-add-stat
export _INFINITY_JOB_="_INFINITY_JOB_"

# header -----------------------------------------------------------------------

_DATE=`date`

echo
echo "################################################################################"
echo "#                          *** INFINITY JOB ***                                #"
echo "#                                                                              #"
echo "###                    Beggining of script execution                        ####"
echo "#                                                                              #"
echo "# # Date: `printf %-67s \"$_DATE\"`# #"
echo "#                                                                              #"
echo "################################################################################"
echo
echo " Initial job information (recovered from transmitted environment):"
echo "--------------------------------------------------------------------------------"
echo " Job name             : $INF_JOB_NAME"
echo " Job name suffix      : $INF_JOB_NAME_SUFFIX"
echo " Job input machine    : $INF_JOB_MACHINE"
echo " Job input path       : $INF_JOB_PATH"
echo " Job storage machine  : $INF_STORAGE_MACHINE"
echo " Job storage path     : $INF_STORAGE_PATH"
echo " Data IN copy mode    : $INF_DATAIN"
echo " Data OUT copy mode   : $INF_DATAOUT"
echo " Job key              : $INF_JOB_KEY"
echo "------------------------------------------------------"
echo " Hostname             : `hostname -f`"
echo " Site support         : $AMS_SITE_SUPPORT"
echo " Site ID              : $INF_SITE_ID"
echo " ABS module version   : $INF_ABS_VERSION"
echo " ABS Root             : $ABS_ROOT"
echo " AMS boot script      : $INF_BOOT_SCRIPT"
echo ""

echo ""
echo "#-------------------------------------------------------------------------------"
echo "# L0 First execution layer ..."
echo "#-------------------------------------------------------------------------------"

# boot AMS ---------------------------------------------------------------------
echo "User identity ..."
echo "UID   : `id`"
echo "Umask : `umask`"
echo

if [ -f "$INF_BOOT_SCRIPT" ]; then
    # boot AMS system
    source $INF_BOOT_SCRIPT
fi

echo "$ site -v activate $INF_SITE_ID"

site -v activate $INF_SITE_ID

if [ $? -ne 0 ]; then
    echo "" >&2
    echo " ERROR: Unable to activate site ($INF_SITE_ID)!" >&2
    echo "        Please send contents of this file to the site support: $AMS_SITE_SUPPORT" >&2
    echo "" >&2
    exit 1
fi

# destroy ams host cache
echo "$ ams-host --nocache"

ams-host --nocache

echo "$ amsmodule --system add abs:$INF_ABS_VERSION"

# here we should use the same version as it was used for job submision
amsmodule --system add abs:$INF_ABS_VERSION

if [ $? -ne 0 ]; then
    echo "" >&2
    echo " ERROR: Unable to add 'abs:$INF_MODULE_VERS' module!" >&2
    echo "        Please send contents of this file to the site support: $AMS_SITE_SUPPORT" >&2

    echo "" >&2
    exit 1
fi

# =============================================================================
# Stage 01 - execute wrapper script +++++++++++++++++++++++++++++++++++++++++++
# =============================================================================

# Restore job environment ...
source $ABS_ROOT/share/scripts/abs-execution-script-L1
if [ $? -ne 0 ]; then exit 1; fi

# Prepare working directory ...
source $ABS_ROOT/share/scripts/abs-execution-script-L2
if [ $? -ne 0 ]; then exit 1; fi

# Copy input job data ...
$ABS_ROOT/share/scripts/abs-execution-script-L3
if [ $? -ne 0 ]; then exit 1; fi

# Start job ...
source $ABS_ROOT/share/scripts/abs-execution-script-L4
if [ $? -ne 0 ]; then exit 1; fi

# Sync data ...
$ABS_ROOT/share/scripts/abs-execution-script-L5
if [ $? -ne 0 ]; then exit 1; fi

# Clean ...
$ABS_ROOT/share/scripts/abs-execution-script-L6
if [ $? -ne 0 ]; then exit 1; fi

# =============================================================================

echo
echo "################################################################################"
echo "#                                                                              #"
echo "# # Date: `printf %-67s \"$_DATE\"`# #"
echo "#                                                                              #"
echo "###                        End of script execution                          ####"
echo "#                                                                              #"
echo "################################################################################"
echo


