#!/bin/bash
# ==============================================================================
# ABS
# (c) 2017, Petr Kulhanek, kulhanek@chemi.muni.cz
# (c) 2012, Petr Kulhanek, kulhanek@chemi.muni.cz
# (c) 2008-2009, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.9
# (c) 2006, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.8
# (c) 2005, Petr Kulhanek, kulhanek@chemi.muni.cz
# based on LCC module v1 - v5
# (c) 2001-2004, Petr Kulhanek, kulhanek@chemi.muni.cz
# ==============================================================================

echo ""
echo "# ------------------------------------------------------------------------------"
echo "# L1: Restore job environment ..."
echo "# ------------------------------------------------------------------------------"

# get configuration items
TMPDIR=`$ABS_ROOT/sbin/abs-get-setup-item INF_TMP_DIR`
if [ $? -ne 0 ]; then TMPDIR="/tmp"; fi
export TMPDIR

INF_SSH_OPTIONS=`$ABS_ROOT/sbin/abs-get-setup-item INF_SSH_OPTIONS`
if [ $? -ne 0 ]; then INF_SSH_OPTIONS="-o StrictHostKeyChecking=no"; fi
export INF_SSH_OPTIONS

INF_RETRY_COUNT=`$ABS_ROOT/sbin/abs-get-setup-item INF_RETRY_COUNT`
if [ $? -ne 0 ]; then INF_RETRY_COUNT="3"; fi
export INF_RETRY_COUNT

INF_RETRY_TIME=`$ABS_ROOT/sbin/abs-get-setup-item INF_RETRY_TIME`
if [ $? -ne 0 ]; then INF_RETRY_TIME="600"; fi
export INF_RETRY_TIME

echo "# Temporary directory : $TMPDIR"
echo "# SSH Options         : $INF_SSH_OPTIONS"
echo "# Retry count         : $INF_RETRY_COUNT"
echo "# Retry time          : $INF_RETRY_TIME"
echo "# Current directory   : `pwd`"
echo "# Input directory     : $INF_INPUT_MACHINE:$INF_INPUT_DIR"
echo "# Storage directory   : $INF_STORAGE_MACHINE:$INF_STORAGE_DIR"


# the full name of the job service files
export INF_WHOLE_NAME="${INF_JOB_NAME}${INF_JOB_NAME_SUFFIX}"

# ------------------------------------------------------------------------------
echo
echo "# Is the input directory local?"

export INF_LOCAL_INPUT_DATA="NO"
if [ -d "$INF_INPUT_DIR" ]; then
    # compare keys
    grep "$INF_JOB_KEY" "$INF_INPUT_DIR/${INF_WHOLE_NAME}.infkey" &> /dev/null
    if [ $? -eq 0 ]; then
        INF_LOCAL_INPUT_DATA="YES"
        echo " > the input dir is local and the keys match!"
    else
        echo " > the input dir is local but the keys do not match, the remote storage or input machine will be used!"
    fi
else
        echo " > the input dir is on the remote storage or input machine!"   
fi

# ------------------------------------------------------------------------------
# copy job info to temporary directory
export _TNAME_="$$.$USER"

echo ""
echo "# Coping the job info file to the temporary directory ..."
inf-retry-cmd inf-copy-from-inputdir "${INF_WHOLE_NAME}.info" "$TMPDIR/${_TNAME_}.info"
if [ $? -ne 0 ]; then exit 1; fi

# correct group ownership
chgrp "`id -g -n`" "$TMPDIR/${_TNAME_}.info"

# ------------------------------------------------------------------------------
echo ""
echo "# Restoring the job environment variables ..."

# restore job shell environment
AMS_EXIT_CODE=0

EVAL_STRING=`$ABS_ROOT/sbin/abs-restore-env "$TMPDIR/${_TNAME_}.info"`
if [ $? -ne 0 ]; then
    echo "" >&2
    echo " >>> ERROR: Unable to restore Infinity environment!" >&2
    echo "" >&2
    exit 1
fi

eval $EVAL_STRING
if [ $? -ne 0 ] || [ "$AMS_EXIT_CODE" != "0" ]; then
    rm -f "$TMPDIR/${_TNAME_}.info"
    exit 1
fi

# ------------------------------------------------------------------------------
# AMS/ABS co-operation

export AMS_NCPUS=$INF_NCPUS
export AMS_NGPUS=$INF_NGPUS
export AMS_NNODES=$INF_NNODES
export AMS_NODEFILE=$PBS_NODEFILE

# ------------------------------------------------------------------------------
# determine INF_MAX_WALLTIME from the job stat
export INF_MAX_WALLTIME=`pqstat -j $INF_JOB_ID | grep Resource_List.walltime | awk '{print $3;}' | tr ":" " " | awk '{ print $1*3600 + $2*60 + $3;}'`

# ------------------------------------------------------------------------------
# restore exported modules

if [ -n "$INF_EXPORTED_MODULES" ]; then
    echo "# Exported modules   : $INF_EXPORTED_MODULES"
else
    echo "# Exported modules   : -none-"
fi

INF_EXPORTED_MODULES=`echo $INF_EXPORTED_MODULES | sed -e 's/|/ /g'`

if [ "$INF_EXPORTED_MODULES" != "" ]; then
    amsmodule --reexported add $INF_EXPORTED_MODULES
else
    echo ""
fi

# ------------------------------------------------------------------------------
# list environment

echo "# Variable                     Value                                            "
echo "# ---------------------------- -------------------------------------------------"
set | grep ^INF_    | sed -s 's/=/ /1'| awk '{ printf("%-30s",$1); for(i=2;i<=NF;i++) printf(" %s",$i); printf("\n"); }'
set | grep ^AMS_    | sed -s 's/=/ /1'| awk '{ printf("%-30s",$1); for(i=2;i<=NF;i++) printf(" %s",$i); printf("\n"); }'
set | grep ^PBS_    | sed -s 's/=/ /1'| awk '{ printf("%-30s",$1); for(i=2;i<=NF;i++) printf(" %s",$i); printf("\n"); }'
set | grep ^TORQUE_ | sed -s 's/=/ /1'| awk '{ printf("%-30s",$1); for(i=2;i<=NF;i++) printf(" %s",$i); printf("\n"); }'

# ------------------------------------------------------------------------------

# FIXME - compatibility mode - set them here so they are not visible in the above lists
export AMS_NCPU=$AMS_NCPUS
export AMS_NGPU=$AMS_NGPUS
export AMS_NNODE=$AMS_NNODES

export INF_NCPU=$AMS_NCPUS
export INF_NGPU=$AMS_NGPUS
export INF_NNODE=$AMS_NNODES

export INF_JOB_PATH=$INF_INPUT_DIR
export INF_JOB_MACHINE=$INF_INPUT_MACHINE





