#!/bin/bash
# ==============================================================================
# ABS
# (c) 2012, Petr Kulhanek, kulhanek@chemi.muni.cz
# (c) 2008-2009, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.9
# (c) 2006, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.8
# (c) 2005, Petr Kulhanek, kulhanek@chemi.muni.cz
# based on LCC module v1 - v5
# (c) 2001-2004, Petr Kulhanek, kulhanek@chemi.muni.cz
# ==============================================================================
#
# required input
# INF_SYNC_MAIN_NODE
# INF_SYNC_WORK_DIR
# INF_SYNC_INPUT_DIR
# INF_SYNC_INPUT_MACHINE
# INF_SYNC_WI_RSYNCOPTS
# INF_SYNC_WHOLE_NAME
# INF_SYNC_ALL

# global setup
INF_SSH_OPTIONS=`$ABS_ROOT/sbin/abs-get-setup-item INF_SSH_OPTIONS`
if [ $? -ne 0 ]; then INF_SSH_OPTIONS="-o StrictHostKeyChecking=no"; fi
export INF_SSH_OPTIONS

#===============================================================================
#-------------------------------------------------------------------------------
#===============================================================================

# we need modified rsync
amsmodule --system add abs-rsync 2> /dev/null

if [ $? -ne 0 ]; then
    echo "" >&2
    echo " >>> ERROR: Unable to add the 'abs-rsync' module!" >&2
    echo "" >&2
    exit 1
fi

if ! [ -e "$ABS_RSYNC" ]; then
    echo "" >&2
    echo " >>> ERROR: '$ABS_RSYNC' is not executable!" >&2
    echo "" >&2
    exit 1
fi

echo "List of files in the working directory:"
echo "========================================================"
ssh -x $INF_SSH_OPTIONS $INF_SYNC_MAIN_NODE "cd $INF_SYNC_WORK_DIR; if [ \$? -ne 0 ]; then echo; exit 1; fi; \ls -l *"

if [ $? -ne 0 ]; then
    exit 1
fi

# fix group name translation
if [ "$HOSTNAME" != "$INF_SYNC_MAIN_NODE" ]; then
    # we are in the job input directory
    INF_LR=`stat "${INF_SYNC_WHOLE_NAME}.info" --format=%G | tr '@' ' ' | awk '{ printf("%s",$2);}'`
    if [ -n "$INF_LR" ]; then
        INF_SYNC_WI_RSYNCOPTS="${INF_SYNC_WI_RSYNCOPTS}@$INF_LR"
    fi
fi

echo ""
echo "rsync setup: $INF_SYNC_WI_RSYNCOPTS"
echo "ssh options: $INF_SSH_OPTIONS"
if [ "$HOSTNAME" == "$INF_SYNC_MAIN_NODE" ]; then
echo "direction:   $INF_SYNC_WORK_DIR/FILE -> $INF_SYNC_INPUT_MACHINE:$INF_SYNC_INPUT_DIR/"
else
echo "direction:   $INF_SYNC_MAIN_NODE:$INF_SYNC_WORK_DIR/FILE -> $PWD/"
fi

# we must use $PWD instead of $INF_SYNC_INPUT_DIR as we can be in different path on other machines,
# for example on a personal computer, where the path might be differnt

echo ""
if [ "$INF_SYNC_ALL" == "YES" ]; then
    echo -n "All files will be synchronized by rsync "
    if [ "$HOSTNAME" == "$INF_SYNC_MAIN_NODE" ]; then
        echo "from the working directory ..."
        $ABS_RSYNC -av $INF_SYNC_WI_RSYNCOPTS -e "ssh -x $INF_SSH_OPTIONS" --exclude "___JOB_IS_RUNNING___" \
              --rsync-path="LOC_RSYNC=rsync; if [ -f $ABS_RSYNC ]; then LOC_RSYNC=$ABS_RSYNC; fi; \$LOC_RSYNC" \
              "$INF_SYNC_WORK_DIR/" "$INF_SYNC_INPUT_MACHINE:$INF_SYNC_INPUT_DIR/" 2>&1 | awk '{ printf("   %s\n",$0); }'
        if [ $? -ne 0 ]; then
            echo "" >&2
            echo " >>> ERROR: Unable to copy all files!" >&2
            echo "" >&2
            exit 1
        fi
    else
        echo "from the input directory ..."
        $ABS_RSYNC -av $INF_SYNC_WI_RSYNCOPTS -e "ssh -x $INF_SSH_OPTIONS" --exclude "___JOB_IS_RUNNING___" \
              --rsync-path="LOC_RSYNC=rsync; if [ -f $ABS_RSYNC ]; then LOC_RSYNC=$ABS_RSYNC; fi; \$LOC_RSYNC" \
              "$INF_SYNC_MAIN_NODE:$INF_SYNC_WORK_DIR/" "$PWD/" 2>&1 | awk '{ printf("   %s\n",$0); }'
        if [ $? -ne 0 ]; then
            echo "" >&2
            echo " >>> ERROR: Unable to copy all files!" >&2
            echo "" >&2
            exit 1
        fi
    fi
    echo "Done."
    echo ""
    exit 0
fi

if [ $# -gt 0 ]; then
    echo "List of files were specified from the command line."
    COUNT=1
    FILES=""
    while [ $# -gt 0 ]; do
        case $1 in
            -h|--help|-v|--verbose|--version)
                # skip
            ;;
            *)
                FILES="$FILES $1"
            ;;
        esac
        shift
    done
    echo ">$FILES"
else
    echo "Please specify files to be synchronized (separated by spaces)..."
    echo -n "> "
    read FILES
fi

if [ "$FILES" == "" ]; then
    echo "" >&2
    echo " >>> ERROR: No files were specified ..." >&2
    echo "" >&2
    exit 1
fi

echo ""

for SFILE in $FILES; do
    echo -n "Copying file '$SFILE' by rsync ... "
    if [ "$SFILE" == "___JOB_IS_RUNNING___" ]; then
        echo "Skipped."
    else
        if [ "$HOSTNAME" == "$INF_SYNC_MAIN_NODE" ]; then
            $ABS_RSYNC -av $INF_SYNC_WI_RSYNCOPTS -e "ssh -x $INF_SSH_OPTIONS" \
                  --rsync-path="LOC_RSYNC=rsync; if [ -f $ABS_RSYNC ]; then LOC_RSYNC=$ABS_RSYNC; fi; \$LOC_RSYNC" \
                  "$INF_SYNC_WORK_DIR/$SFILE" "$INF_SYNC_INPUT_MACHINE:$INF_SYNC_INPUT_DIR/" > /dev/null
            if [ $? -ne 0 ]; then
                echo "" >&2
                echo " >>> ERROR: Unable to copy the file!" >&2
                echo "" >&2
                exit 1
            fi
        else
            $ABS_RSYNC -av $INF_SYNC_WI_RSYNCOPTS -e "ssh -x $INF_SSH_OPTIONS" \
                  --rsync-path="LOC_RSYNC=rsync; if [ -f $ABS_RSYNC ]; then LOC_RSYNC=$ABS_RSYNC; fi; \$LOC_RSYNC" \
                  "$INF_SYNC_MAIN_NODE:$INF_SYNC_WORK_DIR/$SFILE" "$PWD/" > /dev/null
            if [ $? -ne 0 ]; then
                echo "" >&2
                echo " >>> ERROR: Unable to copy the file!" >&2
                echo "" >&2
                exit 1
            fi
        fi
        echo "Done."
    fi
done

echo ""
