#!/bin/bash
# =============================================================================
# ABS
# (c) 2017, Petr Kulhanek, kulhanek@chemi.muni.cz
# (c) 2008-2009, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.9
# (c) 2006, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.8
# (c) 2005, Petr Kulhanek, kulhanek@chemi.muni.cz
# based on LCC module v1 - v5
# (c) 2001-2004, Petr Kulhanek, kulhanek@chemi.muni.cz
# =============================================================================

echo ""
echo "# ------------------------------------------------------------------------------"
echo "# L3: Coping the input data to the working directory ..."
echo "# ------------------------------------------------------------------------------"
echo ""
echo "# Input directory    : $INF_INPUT_MACHINE:$INF_INPUT_DIR"
echo "# Storage directory  : $INF_STORAGE_MACHINE:$INF_STORAGE_DIR"
echo "# Working directory  : $INF_WORK_DIR"
echo "# Data IN copy mode  : $INF_DATAIN"
if [ -n "$INF_EXCLUDED_FILES" ]; then
echo "# Excluded files     : $INF_EXCLUDED_FILES"
else
echo "# Excluded files     : -none-"
fi

echo ""
case $INF_DATAIN in
    keep )
        echo "# Data are left in the working directory, which is presumably the input directory ..."
    ;;
    copy )
        echo "# Data are copied to the main working node only ..."
        inf-retry-cmd inf-rsync-from-inputdir
        if [ $? -ne 0 ]; then exit 1; fi
    ;;
esac






