#!/bin/bash
# =============================================================================
# ABS
# (c) 2017, Petr Kulhanek, kulhanek@chemi.muni.cz
# (c) 2012, Petr Kulhanek, kulhanek@chemi.muni.cz
# (c) 2008, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.9
# (c) 2006, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.8
# (c) 2005, Petr Kulhanek, kulhanek@chemi.muni.cz
# based on LCC module v1 - v5
# (c) 2001-2004, Petr Kulhanek, kulhanek@chemi.muni.cz
# =============================================================================

function abs_write_kill_header()
{
cat << EOF
#!/bin/bash
# ********************************************************************
# WARNING: This script will kill the job, use it with precaution!
#*********************************************************************

if [ "\$1" != "$INF_JOB_KEY" ]; then
    echo >&2
    echo " >>> ERROR: Unable to execute due to incorrect job key!" >&2
    echo >&2
    exit 1
fi

echo ""
echo "Job soft termination initiated ..."

echo ">>>>> JOB SOFT TERMINATION INITIATED UPON USER REQUEST AT `date`" >> "${INF_WHOLE_NAME}.stdout"
EOF
}

# ------------------------------------------------------------------------------

function abs_write_kill_screen()
{
cat << EOF

# activate site and terminal agent module
site activate "$INF_SITE_ID"
amsmodule add "$INF_AGENT_MODULE"

# terminate screen session
screen -d -r "T$INF_JOB_KEY" -X quit
EOF
}

# ------------------------------------------------------------------------------

function abs_write_kill_tigervnc()
{
cat << EOF

# activate site and terminal agent module
site activate "$INF_SITE_ID"
amsmodule add "$INF_AGENT_MODULE"

# terminate vnc display
vncserver -kill ":$INF_VNC_DISPLAY"
EOF
}

# ------------------------------------------------------------------------------

function abs_write_kill_script()
{
cat << EOF

# kill the main job process
kill "$INF_AGENT_PID"
EOF
}

# ------------------------------------------------------------------------------

function abs_write_kill_footer()
{
cat << EOF

# wait until the session is terminated
for((I=0;I<12;I++)); do
    if ! [ -d "/proc/$INF_AGENT_PID" ]; then
        echo
        exit
    fi
    echo ">>> INFO: Waiting until the agent session is terminated ...."
    sleep 5
done

# if not terminated within 60 seconds - kill the process
kill "$INF_AGENT_PID"
sleep 5
if ! [ -d "/proc/$INF_AGENT_PID" ]; then
    echo
    exit
fi
kill -9 "$INF_AGENT_PID"
echo
EOF
}

# ------------------------------------------------------------------------------

echo ""
echo "# ------------------------------------------------------------------------------"
echo "# L4: Starting the job ..."
echo "# ------------------------------------------------------------------------------"
echo ""

# metacentrum hack for non-meta sites
if [ -z "$SCRATCHDIR" ]; then
    export SCRATCHDIR="$INF_WORK_DIR"
fi

# create link to infout

# MetaCentrum
if [ -f "/var/spool/pbs/spool/${INF_JOB_ID}.OU" ]; then
    ln -s "/var/spool/pbs/spool/${INF_JOB_ID}.OU" "${INF_WHOLE_NAME}.tmpinfout"
fi

# IT4I
if [ -f "/var/spool/PBS/spool/${INF_JOB_ID}.OU" ]; then
    ln -s "/var/spool/PBS/spool/${INF_JOB_ID}.OU" "${INF_WHOLE_NAME}.tmpinfout"
fi

# ------------------------------------------------

case $INF_JOB_NAME in
    cli )
        echo "Starting a CLI terminal ..."
        amsmodule add screen
        if [ $? -ne 0 ]; then
            echo "" >&2
            echo " >>> ERROR: Unable to add the 'screen' module!" >&2
            echo "            Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
            echo "" >&2
            exit 1
        fi

        INF_AGENT_MODULE="`amsmodule getactmod screen 2>&1`"
        export INF_AGENT_MODULE

        # disable termcap capabilities
        export SCREENCAP=""
        # start screen terminal and detach from it
        screen -D -m -S "T$INF_JOB_KEY" -c $ABS_ROOT/share/scripts/screenrc &
        INF_AGENT_PID=$!

        echo "Screen session: T$INF_JOB_KEY"
        echo "Screen PID:     $INF_AGENT_PID"

        # catch signals to properly terminate screen session
        trap "kill $INF_AGENT_PID; exit" SIGINT SIGTERM

        # create kill script
        touch "${INF_WHOLE_NAME}.kill"
        if [ $? -ne 0 ]; then
            echo "" >&2
            echo " >>> ERROR: Unable to create kill script '${INF_WHOLE_NAME}.kill'!" >&2
            echo "" >&2
            exit 1
        fi
        chmod 600 "${INF_WHOLE_NAME}.kill"
        abs_write_kill_header >  "${INF_WHOLE_NAME}.kill"
        abs_write_kill_screen >> "${INF_WHOLE_NAME}.kill"
        abs_write_kill_footer >> "${INF_WHOLE_NAME}.kill"

        # setup terminal
        sleep 10  # wait for terminal initialization
        screen -S "T$INF_JOB_KEY" -p 0 -X backtick 100 1 1 pinfo --terminal
        screen -S "T$INF_JOB_KEY" -p 0 -X caption string '%100`'
        screen -S "T$INF_JOB_KEY" -p 0 -X logfile "${INF_WHOLE_NAME}.stdout"
        screen -S "T$INF_JOB_KEY" -p 0 -X log on
        screen -S "T$INF_JOB_KEY" -p 0 -X caption always

        # update info file
        $ABS_ROOT/sbin/abs-update-infofile --agent "$INF_AGENT_MODULE" cliready
        if [ $? -ne 0 ]; then
            echo "" >&2
            echo " >>> ERROR: Unable to update job status in the job info file!" >&2
            echo "" >&2
            kill $SCREEN_PID
            exit 1
        fi

        case $INF_DATAIN in
            copy|shared)
                inf-retry-cmd inf-copy-to-inputdir "$INF_WORK_DIR/${INF_WHOLE_NAME}.info" "${INF_WHOLE_NAME}.info"
            ;;
        esac

        # notify user if requested
        if [ -n "$INF_EMAIL" ]; then
            echo "E-mail notification: $INF_EMAIL"
            pinfo | mail -s "[INFINITY] CLI job $INF_JOB_ID was started" "$INF_EMAIL"
        fi

        # wait for the screen termination
        wait
        export INF_JOB_EXIT_CODE=$?
        if [ $INF_JOB_EXIT_CODE -gt 128 ]; then
            # signal received
            exit 1  # immediatelly exit
        fi
        echo "CLI terminal was terminated."
        ;;
    gui )
        echo "Starting a GUI terminal ..."
        amsmodule add tigervnc
        if [ $? -ne 0 ]; then
            echo "" >&2
            echo " >>> ERROR: Unable to add the 'tigervnc' module!" >&2
            echo "            Please send contents of this output to the site support: $AMS_SITE_SUPPORT" >&2
            echo "" >&2
            exit 1
        fi

        INF_AGENT_MODULE="`amsmodule getactmod tigervnc 2>&1`"
        export INF_AGENT_MODULE

        # generate password
        touch "${INF_WHOLE_NAME}.vncpsw"
        if [ $? -ne 0 ]; then
            echo "" >&2
            echo " >>> ERROR: Unable to create VNC password file '${INF_WHOLE_NAME}.vncpsw'!" >&2
            echo "" >&2
            exit 1
        fi
        chmod 600 "${INF_WHOLE_NAME}.vncpsw"
        uuidgen | vncpasswd -f > "${INF_WHOLE_NAME}.vncpsw"

        # start VNC server
        vncserver -fg -rfbauth "$INF_WORK_DIR/${INF_WHOLE_NAME}.vncpsw" &> "${INF_WHOLE_NAME}.vncid" &

        INF_AGENT_PID=$!

        # catch signals to properly terminate vnc session
        trap "kill $INF_AGENT_PID; exit" SIGINT SIGTERM

        # setup terminal
        sleep 10  # wait for terminal initialization

        echo "VNC PID:     $INF_AGENT_PID"

        INF_VNC_ID="`grep \"^VNCID:\" \"${INF_WHOLE_NAME}.vncid\" | awk '{printf("%s",$2); }'`"
        if [ -z "$INF_VNC_ID" ]; then
            echo "" >&2
            echo " >>> ERROR: Unable to get VNC ID from the vncid file '${INF_WHOLE_NAME}.vncid'!" >&2
            kill $VNCSERVER_PID
            echo "" >&2
            exit 1
        fi
        echo "VNC ID:      $INF_VNC_ID"

        INF_VNC_DISPLAY="`grep \"^VNCDSP:\" \"${INF_WHOLE_NAME}.vncid\" | awk '{printf("%s",$2); }'`"
        if [ -z "$INF_VNC_DISPLAY" ]; then
            echo "" >&2
            echo " >>> ERROR: Unable to get VNC DISPLAY from the vncid file '${INF_WHOLE_NAME}.vncid'!" >&2
            kill $VNCSERVER_PID
            echo "" >&2
            exit 1
        fi
        echo "VNC DISPLAY: $INF_VNC_ID"

        # create empty stdout
        touch "${INF_WHOLE_NAME}.stdout"

        # create kill script
        touch "${INF_WHOLE_NAME}.kill"
        if [ $? -ne 0 ]; then
            echo "" >&2
            echo " >>> ERROR: Unable to create kill script '${INF_WHOLE_NAME}.kill'!" >&2
            echo "" >&2
            exit 1
        fi
        chmod 600 "${INF_WHOLE_NAME}.kill"
        abs_write_kill_header   >  "${INF_WHOLE_NAME}.kill"
        abs_write_kill_tigervnc >> "${INF_WHOLE_NAME}.kill"
        abs_write_kill_footer   >> "${INF_WHOLE_NAME}.kill"

        # update info file
        $ABS_ROOT/sbin/abs-update-infofile --agent "$INF_AGENT_MODULE" --vncid "$INF_VNC_ID" guiready

        if [ $? -ne 0 ]; then
            echo "" >&2
            echo " >>> ERROR: Unable to update job status in the job info file!" >&2
            kill $VNCSERVER_PID
            echo "" >&2
            return 1
        fi

        case $INF_DATAIN in
            copy|shared)
                inf-retry-cmd inf-copy-to-inputdir "$INF_WORK_DIR/${INF_WHOLE_NAME}.info"   "${INF_WHOLE_NAME}.info"
                inf-retry-cmd inf-copy-to-inputdir "$INF_WORK_DIR/${INF_WHOLE_NAME}.vncpsw" "${INF_WHOLE_NAME}.vncpsw"
            ;;
        esac

        # notify user if requested
        if [ -n "$INF_EMAIL" ]; then
            echo "E-mail notification: $INF_EMAIL"
            pinfo | mail -s "[INFINITY] GUI job $INF_JOB_ID was started" "$INF_EMAIL"
        fi

        # wait for the vnc server termination
        wait
        export INF_JOB_EXIT_CODE=$?
        if [ $INF_JOB_EXIT_CODE -gt 128 ]; then
            # signal received
            exit 1  # immediatelly exit
        fi
        echo "GUI terminal was terminated."
        ;;
    * )
        chmod u+x $INF_JOB_NAME

        echo "====================== Begining of the script execution ========================"
        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
        echo " Started at    : `date`"
        echo " Script name   : $INF_JOB_NAME"
        echo " Script output : ${INF_WHOLE_NAME}.stdout"

        # this is used by pkill command to softly kill the job
        ./$INF_JOB_NAME &> ${INF_WHOLE_NAME}.stdout &
        INF_AGENT_PID=$!

        # create kill script
        touch "${INF_WHOLE_NAME}.kill"
        if [ $? -ne 0 ]; then
            echo "" >&2
            echo " >>> ERROR: Unable to create kill script '${INF_WHOLE_NAME}.kill'!" >&2
            echo "" >&2
            exit 1
        fi
        chmod 600 "${INF_WHOLE_NAME}.kill"
        abs_write_kill_header >  "${INF_WHOLE_NAME}.kill"
        abs_write_kill_script >> "${INF_WHOLE_NAME}.kill"
        abs_write_kill_footer >> "${INF_WHOLE_NAME}.kill"

        wait $INF_AGENT_PID
        export INF_JOB_EXIT_CODE=$?

        echo " Finished at   : `date`"
        echo " Exit code     : $INF_JOB_EXIT_CODE"
        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
        echo "========================= End of the script execution =========================="
        ;;
esac

# remove the kill script and link to infout script
rm -f "${INF_WHOLE_NAME}.kill"
unlink "${INF_WHOLE_NAME}.tmpinfout"


