#!/bin/bash
# =============================================================================
# ABS
# (c) 2017, Petr Kulhanek, kulhanek@chemi.muni.cz
# (c) 2008-2009, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.9
# (c) 2006, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.8
# (c) 2005, Petr Kulhanek, kulhanek@chemi.muni.cz
# based on LCC module v1 - v5
# (c) 2001-2004, Petr Kulhanek, kulhanek@chemi.muni.cz
# =============================================================================

echo ""
echo "# ------------------------------------------------------------------------------"
echo "# L5.1: Data in the working directory ..."
echo "# ------------------------------------------------------------------------------"
echo

ls -l

echo ""
echo "# ------------------------------------------------------------------------------"
echo "# L5.2: Copy the working directory to the input directory ..."
echo "# ------------------------------------------------------------------------------"
echo " Data OUT copy mode : $INF_DATAOUT"

# setup rsync options
if [ "$INF_FS_TYPE" == "inconsistent" ]; then
    RSYNC_OPTS="--no-g"
fi

case $INF_DATAOUT in
    keep )
        echo " Data left in the working directory, which is presumably the input directory ..."
    ;;
    copy)
        echo " Data from the main working node are only copied ..."
        inf-retry-cmd inf-rsync-from-inputdir
        if [ $? -ne 0 ]; then exit 1; fi
    ;;
esac

# -----------------------------------------------------------------------------

echo ""
echo " Write the job end info and update the info file ..."

$ABS_ROOT/sbin/abs-update-infofile stop
if [ $? -ne 0 ]; then
    echo "" >&2
    echo " ERROR: Unable to update the job status in the job info file!" >&2
    echo "" >&2
    exit 1
fi

inf-retry-cmd inf-copy-to-inputdir "$INF_WORK_DIR/${INF_WHOLE_NAME}.info" "${INF_WHOLE_NAME}.info"
if [ $? -ne 0 ]; then exit 1; fi

# notify user about the job end
case $INF_JOB_NAME in
    cli )
        ;;
    gui )
        ;;
    * )
        # notify user if requested
        if [ -n "$INF_EMAIL" ]; then
            echo "E-mail notification: $INF_EMAIL"
            pinfo | mail -s "[INFINITY] Job $INF_JOB_ID was finished" "$INF_EMAIL"
        fi
        ;;
esac

# ------------------------------------------------------------------------------

exit 0
