#!/bin/bash
# ==============================================================================
# ABS
# (c) 2023, Petr Kulhanek, kulhanek@chemi.muni.cz
# (c) 2012, Petr Kulhanek, kulhanek@chemi.muni.cz
# (c) 2008-2009, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.9
# (c) 2006, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.8
# (c) 2005, Petr Kulhanek, kulhanek@chemi.muni.cz
# based on LCC module v1 - v5
# (c) 2001-2004, Petr Kulhanek, kulhanek@chemi.muni.cz
# ==============================================================================

INF_AMS_SITE=$INF_GO_SITE_ID
INF_WORK_DIR=$INF_GO_WORK_DIR
INF_AMS_SITE_EMODS=$INF_GO_EXPORTED_MODULES_1
INF_JOB_EMODS=$INF_GO_EXPORTED_MODULES_2

# activate bash profile
# if [ -f /etc/profile ]; then . /etc/profile; fi
if [ -f ~/.bash_profile ]; then . ~/.bash_profile; fi

if [ -z "$AMS_ROOT" ]; then
    source "$INF_GO_BOOT_SCRIPT"
    AMS_ALTERNATIVE_BOOT="YES"
fi

site activate $INF_AMS_SITE 2> /dev/null
if [ $? -ne 0 ]; then
    echo " >>> ERROR: The site ($INF_AMS_SITE) cannot be activated!" >&2
    echo >&2
    exit 1
fi

if [ "$AMS_ALTERNATIVE_BOOT" == "YES" ]; then
    echo ">>>> NOTE: Infinity has been booted using an alternative startup!"
    echo "           In the alternative mode, some functionality might be limited!"
    echo ""
fi

cd $INF_WORK_DIR 2> /dev/null
if [ $? -ne 0 ]; then
    echo " >>> ERROR: The job working/input directory ($INF_WORK_DIR) is not accesible!" >&2
    echo >&2
    exit 1
fi
if [ -n "$INF_AMS_SITE_EMODS" ]; then
    amsmodule add `echo "$INF_AMS_SITE_EMODS" | tr "%" " "` &> /dev/null;
fi
if [ -n "$INF_JOB_EMODS" ]; then
    amsmodule add `echo "$INF_JOB_EMODS" | tr "%" " "` &> /dev/null;
fi
echo "> Site and job exported modules were recovered."
echo ""
      # -- ------------ ------------ --------------- --------------- ----- ----- ----- -------------------------
echo "> WARNING: This shell is not intended for manipulation with the job data because the current umask"
echo "           and effective user group can be incompatible with the job setup!"
echo ""
exec bash -

