#!/bin/bash
# =============================================================================
# ABS
# (c) 2017, Petr Kulhanek, kulhanek@chemi.muni.cz
# (c) 2008-2009, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.9
# (c) 2006, Petr Kulhanek, kulhanek@chemi.muni.cz
# Charon Extension Layer v0.8
# (c) 2005, Petr Kulhanek, kulhanek@chemi.muni.cz
# based on LCC module v1 - v5
# (c) 2001-2004, Petr Kulhanek, kulhanek@chemi.muni.cz
# =============================================================================

echo ""
echo "# ------------------------------------------------------------------------------"
echo "# L5.1a: Data in the working directory ..."
echo "# ------------------------------------------------------------------------------"

case $INF_DATAOUT in
    copy-master)
        for NODE_NAME in `cat $PBS_NODEFILE | sort -u`; do
            echo ""
            echo ">>> $NODE_NAME:$INF_WORK_DIR -----------------------"
            ssh -x "$INF_SSH_OPTIONS" $NODE_NAME "cd $INF_WORK_DIR; ls -la"
        done
        ;;
    keep|copy-shared)
        echo ""
        echo ">>> $INF_MAIN_NODE:$INF_WORK_DIR -------------------"
        ls -la
        ;;
esac

echo ""
echo "# ------------------------------------------------------------------------------"
echo "# L5.1b: Status of filesystems  ..."
echo "# ------------------------------------------------------------------------------"

case $INF_DATAOUT in
    copy-master)
        for NODE_NAME in `cat $PBS_NODEFILE | sort -u`; do
            echo ""
            echo ">>> $NODE_NAME -------------------------------------"
            ssh -x "$INF_SSH_OPTIONS" $NODE_NAME "timeout 30 df -h; if [ \$? -ne 0 ]; then echo \">>> WARNING: the df command was not completed due to an error or timeout.\"; fi;"
        done
        ;;
    keep|copy-shared)
        echo ""
        echo ">>> $INF_MAIN_NODE ---------------------------------"
        timeout 30 df -h
        if [ $? -ne 0 ]; then
            echo ">>> WARNING: the df command was not completed due to an error or timeout."
        fi
        ;;
esac

echo ""
echo "# ------------------------------------------------------------------------------"
echo "# L5.2: Coping the working directory to the input directory ..."
echo "# ------------------------------------------------------------------------------"
echo ""
echo "# Input directory    : $INF_INPUT_MACHINE:$INF_INPUT_DIR"
echo "# Storage directory  : $INF_STORAGE_MACHINE:$INF_STORAGE_DIR"
echo "# Working directory  : $INF_WORK_DIR"
echo "# Data OUT copy mode : $INF_DATAOUT"

echo ""
case $INF_DATAOUT in
    keep)
        echo "# Data are left in the working directory, which is presumably the input directory ..."
    ;;
    copy-master|copy-shared)
        echo "# Data are copied from the main working node only ..."
        inf-retry-cmd inf-rsync-to-inputdir
        if [ $? -ne 0 ]; then exit 1; fi
    ;;
esac

# -----------------------------------------------------------------------------

echo ""
echo "# Write the job end and update the info file in the input directory ..."

$ABS_ROOT/sbin/abs-update-infofile stop
if [ $? -ne 0 ]; then
    echo "" >&2
    echo " >>> ERROR: Unable to update the job status in the job info file!" >&2
    echo "" >&2
    exit 1
fi

inf-retry-cmd inf-copy-to-inputdir "$INF_WORK_DIR/${INF_WHOLE_NAME}.info" "${INF_WHOLE_NAME}.info"
if [ $? -ne 0 ]; then exit 1; fi

# notify user about the job end
case $INF_JOB_NAME in
    cli )
        ;;
    gui )
        ;;
    * )
        # notify user if requested
        if [ -n "$INF_EMAIL" ]; then
            echo ""
            echo "# E-mail notification: $INF_EMAIL"
            pinfo | mail -s "[INFINITY] Job $INF_JOB_ID was finished" "$INF_EMAIL"
        fi
        ;;
esac

